Refactor
ChangePlusPlusVandy/bookem-admin pull request #48
Opened 2024-02-25 22:32 UTC by manishacharya60

**Frontend:**

Added popup design for new admin button.

**Backend:**

Implemented the popup window to create new admin into the database collection

2024-02-27 20:31 UTC, JiashuHarryHuang requested changes

2024-02-27 20:31 UTC, JiashuHarryHuang commented on components/Forms/CreateAdminPopupWindow.tsx
> +  };
After creating the admin, should show a message that alarms the user about it, either success or failure. You can use antd [message](https://ant.design/components/message)

2024-02-27 20:31 UTC, JiashuHarryHuang commented on pages/api/admin/index.ts
> +        }
Before you insert the user, can you first check if the current user has an admin status?

2024-03-24 21:40 UTC, manishacharya60 commented
Implemented the message feature

2024-03-25 20:07 UTC, JiashuHarryHuang approved these changes
LGTM!

2024-03-25 20:07 UTC, merged